// Report language, chosen per project.
//
// The code is English; the REPORT is read by whoever reviews the PR, and that
// audience is per-project — so the language is data, not code: the baseline
// json carries `"language": "en" | "pt"` and every string that reaches the
// report comes from here. Console/CLI messages stay English: they are
// operational output for whoever runs the gate, not part of the deliverable.
//
// Metric labels and sections are NOT here: they live in the project's
// `quality-baseline.json`, which already makes them per-project by nature.

export type Language = 'en' | 'pt';

export interface GateStrings {
  reportTitle: string;
  statusPassed: string;
  statusFailed: (count: number) => string;
  baselineChangedNotice: readonly string[];
  tableHeader: string;
  regressionsTitle: string;
  ratchetAdvice: readonly string[];
  baselineOriginSuffix: (origin: string) => string;
  footer: (generatedAt: string, originSuffix: string) => string;
  metricNotInBaseline: (metric: string) => string;
  metricRegressed: (label: string, from: string, to: string, kind: string) => string;
  floorWord: string;
  baselineWord: string;
  fileRegressed: (file: string, from: number, to: number) => string;
  pureRulesTitle: (count: number, dirs: string) => string;
  filesOverLimitTitle: (limit: number, count: number) => string;
  explicitAnyTitle: (count: number) => string;
  uncoveredFilesTitle: (count: number) => string;
  uncoveredFileItem: (file: string, lines: number, percent: number) => string;
}

const EN: GateStrings = {
  reportTitle: '## Quality gate',
  statusPassed: '**Status:** ✅ Passed',
  statusFailed: (count) => `**Status:** ❌ Failed — ${count} regression(s)`,
  baselineChangedNotice: [
    '> ⚠️ This PR changes `quality-baseline.json`. Re-freezing is legitimate, but it is',
    '> a decision — check the reason in the commit body before approving.',
  ],
  tableHeader: '| Metric | Baseline | Current | Δ |',
  regressionsTitle: '### Regressions',
  ratchetAdvice: [
    'The ratchet only moves one way. If the regression is deliberate, re-freeze with',
    '`pnpm quality --update-baseline` and explain the reason in the commit body.',
  ],
  baselineOriginSuffix: (origin) => ` · baseline from \`${origin}\``,
  footer: (generatedAt, originSuffix) =>
    `<sub>Generated by \`scripts/quality/gate.mts\` at ${generatedAt}${originSuffix}</sub>`,
  metricNotInBaseline: (metric) =>
    `metric \`${metric}\` is not in the baseline — run with \`--update-baseline\` to freeze it`,
  metricRegressed: (label, from, to, kind) => `${label} went from ${from} to ${to} (${kind})`,
  floorWord: 'floor',
  baselineWord: 'baseline',
  fileRegressed: (file, from, to) =>
    `\`${file}\` went from ${from} to ${to} uncovered lines`,
  pureRulesTitle: (count, dirs) => `Pure rules outside ${dirs} (${count})`,
  filesOverLimitTitle: (limit, count) => `Files over ${limit} lines (${count})`,
  explicitAnyTitle: (count) => `Files with explicit \`any\` (${count})`,
  uncoveredFilesTitle: (count) => `Files with uncovered lines (${count})`,
  uncoveredFileItem: (file, lines, percent) =>
    `\`${file}\` — ${lines} lines · ${percent}% covered`,
};

const PT: GateStrings = {
  reportTitle: '## Portão de qualidade',
  statusPassed: '**Status:** ✅ Aprovado',
  statusFailed: (count) => `**Status:** ❌ Reprovado — ${count} regressão(ões)`,
  baselineChangedNotice: [
    '> ⚠️ Este PR altera o `quality-baseline.json`. Recongelar é legítimo, mas é',
    '> decisão — confira o motivo no corpo do commit antes de aprovar.',
  ],
  tableHeader: '| Métrica | Baseline | Atual | Δ |',
  regressionsTitle: '### Regressões',
  ratchetAdvice: [
    'A catraca só anda num sentido. Se a piora for deliberada, recongele com',
    '`pnpm quality --update-baseline` e explique o motivo no corpo do commit.',
  ],
  baselineOriginSuffix: (origin) => ` · baseline de \`${origin}\``,
  footer: (generatedAt, originSuffix) =>
    `<sub>Gerado por \`scripts/quality/gate.mts\` em ${generatedAt}${originSuffix}</sub>`,
  metricNotInBaseline: (metric) =>
    `métrica \`${metric}\` não está no baseline — rode com \`--update-baseline\` para congelá-la`,
  metricRegressed: (label, from, to, kind) => `${label} passou de ${from} para ${to} (${kind})`,
  floorWord: 'piso',
  baselineWord: 'baseline',
  fileRegressed: (file, from, to) =>
    `\`${file}\` passou de ${from} para ${to} linhas descobertas`,
  pureRulesTitle: (count, dirs) => `Regra pura fora de ${dirs} (${count})`,
  filesOverLimitTitle: (limit, count) => `Arquivos acima de ${limit} linhas (${count})`,
  explicitAnyTitle: (count) => `Arquivos com \`any\` explícito (${count})`,
  uncoveredFilesTitle: (count) => `Arquivos com linha descoberta (${count})`,
  uncoveredFileItem: (file, lines, percent) =>
    `\`${file}\` — ${lines} linhas · ${percent}% coberto`,
};

const STRINGS: Record<Language, GateStrings> = { en: EN, pt: PT };

/** Unknown or absent language falls back to English - never crashes the gate. */
export function stringsFor(language: string | undefined): GateStrings {
  return language === 'pt' ? STRINGS.pt : STRINGS.en;
}
